package com.bindstone.portfolio.entity;

import lombok.Builder;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Currency History Object
 */
@Entity(name = "PF_CURRENCY_HISTORY")
@Builder
@Data
public class CurrencyHistory {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "currency_id", referencedColumnName = "id", nullable = false, insertable = true, updatable = false)
    private Currency currency;

    private LocalDateTime valueDate;

    private BigDecimal rate;

    // GETTER; SETTER; TOSTRING; HASHCODE; EQUALS; BUILDER generated by Lombok
}
