language: java
jdk:
- oraclejdk8
before_install:
- cd ng-portfolio-core
- ls
- mvn -N io.takari:maven:wrapper
- chmod +x mvnw
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarqube:
    token:
      secure: ${sonar_token}
script:
- mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent cobertura:cobertura sonar:sonar jacoco:report coveralls:report -DrepoToken=${coveralls_token} -Dsonar.projectKey=bindstone_ng-portfolio -Dsonar.organization=bindstone-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${sonar_token}
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
